//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameItems.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&apos;games&apos;:[{&apos;id&apos;:1,&apos;value&apos;:{&apos;title&apos;:&apos;Uncharted 4&apos;,&apos;description&apos;:&apos;For the first time ever in Uncharted history, drive vehicles during gameplay&apos;,&apos;by&apos;:&apos;Sony&apos;,&apos;platform&apos;:[&apos;PS4&apos;],&apos;age_rating&apos;:&apos;16&apos;,&apos;likes&apos;:100,&apos;comments&apos;:[{&apos;user&apos;:&apos;bob&apos;,&apos;message&apos;:&apos;Cracking game far too much cinematic&apos;,&apos;dateCreated&apos;:&apos;2011-01-03&apos;,&apos;like&apos;:6},{&apos;user&apos;:&apos;testingPriest&apos;,&apos;message&apos;:&apos;Not enough shooting for me,far too easy &apos;,&apos;dateCreated&apos;:&apos;2011-04-02&apos;,&apos;like&apos;:5}]}},{&apos;id&apos;:2,&apos;value&apos;:{&apos;title&apos;:&apos;Uncharted 4&apos;,&apos;description&apos;:&apos;For the first time ever in [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SampleJsonData {
            get {
                return ResourceManager.GetString("SampleJsonData", resourceCulture);
            }
        }
    }
}
